# 开发环境配置

spring:
  # 开发环境数据源，使用H2内存数据库方便开发
  datasource:
    url: jdbc:mysql://localhost:3306/whale_tide_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      # 开发环境可以减少连接数
      initial-size: 3
      min-idle: 3
      max-active: 10

  # 开发环境Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0


# 开发环境日志级别
logging:
  level:
    root: info
    com.whaletide: debug
    # 打印SQL语句
    com.whaletide.common.mapper: debug
    org.springframework.web: debug
    org.springframework.security: debug

# 开发环境指定存储路径
file:
  upload:
    path: D:/code/project/WhaleTide-1/WhaleTide/dev/upload-files

# 开发环境JWT token过期时间设置为1小时，方便测试
jwt:
  expiration: 3600 